fix(wit.ai): remove async keyword from abstract method
remove async keyword from abstract method declaration, as required by TypeScript, error TS1243:
'async' modifier cannot be used with 'abstract' modifier.